---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: webapp
    app.kubernetes.io/part-of: ""
    app.kubernetes.io/managed-by: ""
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        app.kubernetes.io/name: webapp
        app.kubernetes.io/instance: ""
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: webapp
        app.kubernetes.io/part-of: ""
        app.kubernetes.io/managed-by: ""
    spec:
      # ### Node Selection
      # nodeSelector:
      #   node-select-test: "true"
      ### Node Affinity
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: node-select-test
      #               operator: In
      #               values:
      #                 - "true"
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 25
      #         preference:
      #           matchExpressions:
      #             - key: node-select-preferred
      #               operator: In
      #               values:
      #                 - "yes"
      #       - weight: 75
      #         preference:
      #           matchExpressions:
      #             - key: node-select-preferred
      #               operator: DoesNotExist
      #             - key: node-select-preferred-2
      #               operator: In
      #               values:
      #                 - "yes"
      # ### Pod Affinity & Anti-Affinity
      # # Don't run on master nodes
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: node-role.kubernetes.io/control-plane
      #               operator: NotIn
      #               values:
      #                 - "true"
      # # Don't run webapps on the same nodes with the mongoDB pods
      # podAntiAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #               - "mongodb"
      #       topologyKey: "topology.kubernetes.io/hostname"
      ### Tolerations
      # tolerations:
      #   - key: "compute"
      #     value: "gpu"
      #     operator: "Equal"
      #     effect: "NoSchedule"
      containers:
        - name: mongodb
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets # Name of the secret resource
                  key: mongodb-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets # Name of the secret resource
                  key: mongodb-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service # Acts as the endpoint for the service
spec:
  type: NodePort
  selector:
    app: webapp # Used to find pods that the service should redirect to
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
