---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: "{{ .Values.appNameMongo }}"
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: "MongoDB"
    app.kubernetes.io/managed-by: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.appNameMongo }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appNameMongo }}"
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: ""
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: "MongoDB"
        app.kubernetes.io/managed-by: "Helm"
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webapp-mongodb-secrets # Name of the secret resource
                  key: mongodb-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-mongodb-secrets # Name of the secret resource
                  key: mongodb-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # Acts as the endpoint for the service
spec:
  selector:
    app: "{{ .Values.appNameMongo }}" # Used to find pods that the service should redirect to
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
