---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "webapp-mongodb-secrets"
  labels:
    app.kubernetes.io/name: webapp-mongodb-secrets
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: ""
    app.kubernetes.io/part-of: "MongoDB"
    app.kubernetes.io/managed-by: "Helm"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-secret-store
    kind: ClusterSecretStore
  target:
    name: "webapp-mongodb-secrets"
    creationPolicy: Owner
  data:
    - secretKey: "mongodb-user"
      remoteRef:
        key: "kv-v2/webapp-1/dev/mongo"
        property: "mongodb-user"
    - secretKey: "mongodb-password"
      remoteRef:
        key: "kv-v2/webapp-1/dev/mongo"
        property: "mongodb-password"
