---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.externalSecrets.mongo.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.externalSecrets.mongo.name }}"
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: ""
    app.kubernetes.io/part-of: "MongoDB"
    app.kubernetes.io/managed-by: "Helm"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "{{ .Values.externalSecrets.mongo.secretStoreRef_name }}"
    kind: "{{ .Values.externalSecrets.mongo.secretStoreRef_kind }}"
  target:
    name: "{{ .Values.externalSecrets.mongo.target_name }}"
    creationPolicy: Owner
  data:
    - secretKey: "mongodb-user"
      remoteRef:
        key: "kv-v2/webapp-1/dev/mongo"
        property: "mongodb-user"
    - secretKey: "mongodb-password"
      remoteRef:
        key: "kv-v2/webapp-1/dev/mongo"
        property: "mongodb-password"
