---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "webapp-mongodb-secrets"
  namespace: "default"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-secret-store
    kind: ClusterSecretStore
  target:
    name: "webapp-mongodb-secrets"
    creationPolicy: Owner
  data:
    - secretKey: "mongodb-user"
      remoteRef:
        key: "kv-v2/webapp-1/dev/mongo"
        property: "mongodb-user"
    - secretKey: "mongodb-password"
      remoteRef:
        key: "kv-v2/webapp-1/dev/mongo"
        property: "mongodb-password"
