---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "mosquitto-secret-file"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "mosquitto-secret-file"
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: ""
    app.kubernetes.io/part-of: "Mosquitto"
    app.kubernetes.io/managed-by: "Helm"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "{{ .Values.externalSecrets.mosquitto.secretStoreRef_name }}"
    kind: "{{ .Values.externalSecrets.mosquitto.secretStoreRef_kind }}"
  target:
    name: "mosquitto-secret-file"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret.file: |
          {{ `{{ .secret_file }}` }}
  data:
    - secretKey: "secret_file"
      remoteRef:
        key: "kv-v2/app-mosquitto/dev/config_secrets"
        property: "secret_file"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "mosquitto-config-file"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "mosquitto-config-file"
    app.kubernetes.io/instance: ""
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: ""
    app.kubernetes.io/part-of: "Mosquitto"
    app.kubernetes.io/managed-by: "Helm"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "{{ .Values.externalSecrets.mosquitto.secretStoreRef_name }}"
    kind: "{{ .Values.externalSecrets.mosquitto.secretStoreRef_kind }}"
  target:
    name: "mosquitto-config-file"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mosquitto.conf: |
          log_dest {{ .Values.mqtt_config_log_dest }}
          log_type {{ .Values.mqtt_config_log_type }}
          log_timestamp {{ .Values.mqtt_config_log_timestamp }}
          listener {{ .Values.mqtt_config_listener }}
          # username {{ `{{ .mqtt_username }}` }}
          # password {{ `{{ .mqtt_password }}` }}
  data:
    - secretKey: "mqtt_username"
      remoteRef:
        key: "kv-v2/app-mosquitto/dev/config_secrets"
        property: "mqtt_username"
    - secretKey: "mqtt_password"
      remoteRef:
        key: "kv-v2/app-mosquitto/dev/config_secrets"
        property: "mqtt_password"
